-- 오프라인/온라인 판매 데이터 통합하기 (L4)
SELECT ONLINE.SALES_DATE, ONLINE.PRODUCT_ID, USER_ID, ONLINE.SALES_AMOUNT
FROM ONLINE_SALE AS ONLINE
WHERE ONLINE.SALES_DATE LIKE '2022-03%'
UNION ALL
SELECT OFFLINE.SALES_DATE, OFFLINE.PRODUCT_ID, NULL AS USER_ID, OFFLINE.SALES_AMOUNT
FROM OFFLINE_SALE AS OFFLINE
WHERE OFFLINE.SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
